### ISSUE TITLE
Vagrant plugin `vagrant-triggers` not installed automatically

### ISSUE THREAD

**Issue by dobrynski** [hassio-addons/hassio-vagrant#1]
Hi,

Just thought it might be worth mentioning that the vagrant-triggers plugin is required, otherwise you get the error:
```
vagrant up hassio
A required vagrant plugin is missing: vagrant-triggers
```
After installing vagrant you have to:
```
vagrant plugin install vagrant-triggers
```
Regards,
Michal

**Comment by frenck** [comment]
Thanks for the suggestion @mihalski!

It is true, it requires the plugin, nevertheless, it will try to resolve that requirement by itself. 
So the specific installation requirement should not be necessary.

Nevertheless, I guess there is no harm in adding it to the documentation.

**Comment by dobrynski** [comment]
Really? When I tried to run it without the plugin it exited after the warning:
```
Fortress:hassio michal$ time vagrant up hassio
A required vagrant plugin is missing: vagrant-triggers
Required plugin missing.

real	0m0.906s
user	0m0.605s
sys	0m0.116s
Fortress:hassio michal$
```
I was timing to see if it would take 10 minutes :) Closer to 15-20 on my crappy internet :P

**Comment by frenck** [comment]
Hmmm... it should. Maybe there is a bug in that logic.
Will check that asap.

I will change the labels on this issue for now...

**Comment by frenck** [comment]
Link to the code that should trigger the dependency question:
https://github.com/hassio-addons/hassio-vagrant/blob/fe28a6fe461c9c01c1b2e08a51ff619ab73b4770/Vagrantfile#L70

**Comment by frenck** [comment]
Issue confirmed this is a coding error on my end.

**Comment by frenck** [comment]
@mihalski This issue is fixed in the current master branch, thus a fix will be included in the next release.
