### ISSUE TITLE
[Question] How to change the source of ubuntu ?   I need change the source cn.archive.ubuntu.com 

### ISSUE THREAD

**Issue by chaim007** [hassio-addons/hassio-vagrant#10]
# Problem/Motivation

the default source of ubuntu is very slow in china . I want change it to a mirror in China.
so how to change it ?

**Comment by frenck** [comment]
This vagrant setup uses the official "ubuntu/xenial64" box, made by Ubuntu and is in no way changing any of the default. If there is a Vagrant image available with more sane default for your setup, you can change that in the `configuration.yml` located in the root of this repository.
