### ISSUE TITLE
Vagrant now has Triggers built in

### ISSUE THREAD

**Issue by m-e-h** [hassio-addons/hassio-vagrant#11]
# Problem/Motivation

> Vagrant 2.1+ includes it's own trigger implementation. This makes the `vagrant-triggers` plugin unnecessary and throw console warnings with newer versions of Vagrant. 
https://www.vagrantup.com/docs/triggers/

## Expected behavior

> No additional plugins to install and no warnings in the terminal.

## Actual behavior

> Warnings

## Steps to reproduce

> Try the current Vagrant release
> https://www.vagrantup.com/downloads.html

## Proposed changes

> This seems to work for me
> https://github.com/m-e-h/hassio-vagrant/blob/master/Vagrantfile#L171-L176
> I can test a bit more and do a PR if you'd like.

<blockquote><img src="https://www.vagrantup.com/assets/images/og-image-32e5f237.png" width="48" align="right"><div><img src="/assets/images/favicons/favicon-16x16-68af4fd2.png" height="14"> Vagrant by HashiCorp</div><div><strong><a href="https://www.vagrantup.com/docs/triggers/index.html">Vagrant Triggers - Vagrant by HashiCorp</a></strong></div><div>Introduction to Vagrant Triggers</div></blockquote>
<blockquote><img src="https://www.vagrantup.com/assets/images/og-image-32e5f237.png" width="48" align="right"><div><img src="/assets/images/favicons/favicon-16x16-68af4fd2.png" height="14"> Vagrant by HashiCorp</div><div><strong><a href="https://www.vagrantup.com/downloads.html">Download - Vagrant by HashiCorp</a></strong></div><div>This page lists all the available downloads for Vagrant.</div></blockquote>
<blockquote><img src="https://avatars1.githubusercontent.com/u/3585901?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/m-e-h/hassio-vagrant">m-e-h/hassio-vagrant</a></strong></div><div>hassio-vagrant - Vagrant box running Hass.io / Home Assistant</div></blockquote>

**Comment by frenck** [comment]
Awesome!
Feel free to open a PR 👍

**Comment by frenck** [comment]
This has been fixed on the master branch and will be included in the next release.
Thank you for reporting in this issue/improvement.
