### ISSUE TITLE
vm.synced_folder 'type:' is handled by Vagrant automatically

### ISSUE THREAD

**Issue by m-e-h** [hassio-addons/hassio-vagrant#17]
# Problem/Motivation

My Ubuntu 18.04.1 desktop throws the following error on `vagrant up`
```shell
It appears your machine doesn't support NFS, or there is not an
adapter to enable NFS on this machine for Vagrant. Please verify
that `nfsd` is installed on your machine, and try again. If you're
on Windows, NFS isn't supported. If the problem persists, please
contact Vagrant support.
```
Vagrant should already detects the synced_folder type so this logic may not be needed in the Vagrantfile. https://www.vagrantup.com/docs/synced-folders/basic_usage.html#type
## Proposed changes
You could probably remove the `type:` all together https://github.com/hassio-addons/hassio-vagrant/blob/master/Vagrantfile#L136
Or if Windows is an issue, leaving the `else` empty seems to work for me 
`RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/ ? 'smb' : ''`

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/hassio-vagrant">hassio-addons/hassio-vagrant</a></strong></div><div>Vagrant box running Hass.io / Home Assistant. Contribute to hassio-addons/hassio-vagrant development by creating an account on GitHub.</div></blockquote>

**Comment by frenck** [comment]
My suggestion would be: Update the installation part of the manual to incorporate the NFS part for Linux based systems.

Automatic is certainly an option, I definitely would not recommend it. E.g. having is fallback to vagrant or rsync sharing, is really problematic in development (which is the goal for this setup).

**Comment by m-e-h** [comment]
Apparently the terminal message I posted above isn't accurate or very helpful for Ubuntu users. 
`nfsd` isn't available in the Ubuntu repositories. 

According to this https://github.com/hashicorp/vagrant/issues/1534 
An extra step of `sudo apt-get install nfs-common nfs-kernel-server` is needed to get NFS going on Ubuntu.

I'll try to test this out soon.

**Comment by frenck** [comment]
@m-e-h No need to test, I know this is the things needed.
