### ISSUE TITLE
No guest IP was given to the Vagrant core NFS helper. Shares not mounted

### ISSUE THREAD

**Issue by potgieterdl** [hassio-addons/hassio-vagrant#20]
# Problem/Motivation

> on running `vagrant up hassio` for the first time (v1.1.0) it throws the follow issue on startup
```
==> hassio: Machine booted and ready!
==> hassio: Checking for guest additions in VM...
==> hassio: Setting hostname...
==> hassio: Configuring and enabling network interfaces...
No guest IP was given to the Vagrant core NFS helper. This is an
internal error that should be reported as a bug.
```

When i run it a second time, it starts fine. The issue is that it looks like the shares arent mounted correctly. If i look at the configuration.yml it should have mounted a couple of folders in the vm, but they dont seem to get mounted.

This means that when i have a new addon under the .../hassio/addons folder it isnt picked up. this might be two issues or related. not sure

## Expected behavior

> No error, and shared to be mounted correctly for addon development to work

## Actual behavior

> Failure on first `vagrant up hassio` and no shared folders on second `vagrant up hassio` 

## Steps to reproduce

> git clone https://github.com/hassio-addons/hassio-vagrant.git hassio-dev
cd hassio-dev
vagrant up hassio

## Proposed changes

> None unfortunitly

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/hassio-vagrant">hassio-addons/hassio-vagrant</a></strong></div><div>Vagrant box running Hass.io / Home Assistant. Contribute to hassio-addons/hassio-vagrant development by creating an account on GitHub.</div></blockquote>

**Comment by frenck** [comment]
Could you please provide some information on the systems used?

- Host OS & Version
- NFS installed? Which version?
- Vagrant version
- VirtualBox Version
- VirtualBox Guest additions installed? Version?
- ~~Version of `hassio-vagrant`.~~

**Comment by potgieterdl** [comment]
MacOS 10.13.6 (upgrading to Mojave now)
Virtualbox 5.2.20
VB Ext Pack 5.2.20
Vagrant 2.2.0

After fiddling a bit, i have notices
1. starting against my wifi connection creates the above error `No guest IP was given to the Vagrant core NFS helper.`
2. starting againt my lan connection (wasnt plugged in before) go's further to the point of creating the shares and adding them into the /etc/exports file, but fails then with the error  `Access denied` when trying to run the mount command `mount -o 172.x.x.x:/home/xxx/hassio/addons ...`

Will try again now post the upgrade to mojave

**Comment by danielwelch** [comment]
I am having this same issue with:
MacOS 10.14
Virtualbox 5.2.20 (no extension pack)
Vagrant 2.2.0

**Comment by frenck** [comment]
I've been able to reproduce the issue. It seems like an issue with Vagrant unable to find the host-only network when it is not primary.

https://github.com/hassio-addons/hassio-vagrant/blob/master/Vagrantfile#L98

It seems like swapping line 98 & 99 solves the issue, nevertheless, in my test, is caused the public interface to have 2 IP's instead of just one.

Could any of you test swapping line 98 & 99?

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/hassio-vagrant">hassio-addons/hassio-vagrant</a></strong></div><div>Vagrant box running Hass.io / Home Assistant. Contribute to hassio-addons/hassio-vagrant development by creating an account on GitHub.</div></blockquote>

**Comment by potgieterdl** [comment]
testing now

**Comment by potgieterdl** [comment]
FYI, incase you run on 10.14 Mojave and get issue setting /etc/exports or starting nfsd - https://www.cubewebsites.com/blog/software/quick-fix-macos-mojave-vagrant-error-tee-etc-exports-operation-not-permitted/

<blockquote><div>Cube Websites Blog</div><div><strong><a href="https://www.cubewebsites.com/blog/software/quick-fix-macos-mojave-vagrant-error-tee-etc-exports-operation-not-permitted/">Quick Fix: MacOS Mojave Vagrant Error - tee: /etc/exports: Operation not permitted - Cube Websites Blog</a></strong></div><div>If you’ve updated to the newly released MacOS Mojave release then you might find the following issue when starting your vagrant box with NFS mounting: Preparing to edit /etc/exports. Administrator privileges will be required… Password: tee: /etc/exports: Operation not permitted tee: /etc/exports: Operation not permitted tee: /etc/exports: Operation not permitted You can quickly fix this …</div></blockquote>

**Comment by potgieterdl** [comment]
and it works, swapping line 98 and 99 around now starts perfect and has folders mounted

STEPS:
`vagrant destroy hassio`
`vi Vagrantfile`
 - swap line 99 `machine.vm.network 'private_network', type: 'dhcp'` with 98 `machine.vm.network 'public_network', type: 'dhcp'`
`cat /etc/exports` - mine was nice and empty
`vagrant up hassio`
post startup
 - `vagrant ssh hassio`
 - `ls -ltr /usr/share/hassio/addons/local/` -> showing folders from local machine in the addons local fonder

**Comment by frenck** [comment]
Thanks for testing @potgieterdl, Will adjust the codebase asap to reflect this change.
