### ISSUE TITLE
Incorrect audio device name for Windows

### ISSUE THREAD

**Issue by saicrazyfire** [hassio-addons/hassio-vagrant#23]
# Problem/Motivation

Audio device parameter in the Vagrantfile is named incorrectly for Windows.

Running ```vagrant up hassio``` fails on Windows 10 with this error:

> VBoxManage.exe: error: Invalid --audio argument 'coreaudio'

## Steps to reproduce
Run ```vagrant up hassio``` on a Windows 10 v1809

## Proposed changes

As found in another Github issue (https://github.com/paulsturgess/mopidy-vagrant/issues/3)

> This depends on your host OS: "coreaudio" is only available on a Mac OS host. For a Windows host use "dsound". Linux gives you a couple of options ("alsa", "pulse").

Change line 121 in the Vagrantfile from ```coreaudio``` to ```dsound```

**Comment by frenck** [comment]
Thanks for opening an issue, nevertheless, I'm not a Windows user and haven't touched the OS in the past 11 years (and not planning on doing so).

If you (or someone else) can provide a fix, then I'll be more than happy to add it in.

**Comment by frenck** [comment]
Fixed in #24
