### ISSUE TITLE
hassio install fails

### ISSUE THREAD

**Issue by madereddy** [hassio-addons/hassio-vagrant#33]
# Problem/Motivation

> Hassio install fails when it reaches devices.

## Expected behavior

> Installs in one shot when running the commands

## Actual behavior

> Error when standing up the hassio container.

hassio: Device "enp0s9" does not exist.

## Steps to reproduce

Run the standard installs

## Proposed changes

Im assuming its a device issue with the hassio install

**Comment by madereddy** [comment]
LOGS:    

hassio: Download complete
    hassio: fac26901c311:
    hassio: Pull complete
    hassio: Digest: sha256:cc226d8a06b6d5e24b44a4f10d0d1fd701741e84a852adc6d40bef9424a000ec
    hassio: Status: Downloaded newer image for portainer/portainer:latest
    hassio: 9d228f4fcd2108b458fd345b240858e62606e8521ea0500414b190ece8d8708e
    hassio: portainer
    hassio: [Info] Install supervisor Docker container
    hassio: [Info] Install supervisor startup scripts
    hassio: Created symlink /etc/systemd/system/multi-user.target.wants/hassio-supervisor.service → /etc/systemd/system/hassio-supervisor.service.
    hassio: [Info] Install AppArmor scripts
    hassio: Created symlink /etc/systemd/system/multi-user.target.wants/hassio-apparmor.service → /etc/systemd/system/hassio-apparmor.service.
    hassio: [Info] Run Hass.io
    hassio: Device "enp0s9" does not exist.

**Comment by madereddy** [comment]
Windows 10 box, i5 4790k, 32GB RAM.

**Comment by sinclairpaul** [comment]
Are you sure it isn't this line that fails?
https://github.com/hassio-addons/hassio-vagrant/blob/a10254264218a460bb650af06d5a270bd0ac3d3b/provision.sh#L143
Can you confirm the interface names in the VM?  You could comment those lines out temporarily in the provision script.

Edit - A better way would probably to comment the post_up_message task for troubleshooting.

**Comment by sinclairpaul** [comment]
Going to close this for now, as after all its really a dev tool, if you need assistance I would recommend jumping on Discord.
