### ISSUE TITLE
Requested NFS version or transport protocol is not supported

### ISSUE THREAD

**Issue by Limych** [hassio-addons/hassio-vagrant#35]
# Problem/Motivation

Command `vagrant up` is falls on Windows

## Expected behavior

> (What you expected to happen)

## Actual behavior

```
> vagrant up
[… some lines skipped …]
==> hassio: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp,vers=3,udp,nolock 0.0.0.0:/C/Users/User/PyCharmWorkspace/hassio-vagrant/addons /usr/share/hassio/addons/local

Stdout from the command:



Stderr from the command:

mount.nfs: requested NFS version or transport protocol is not supported

Process finished with exit code 1
```

## Steps to reproduce

I've just install on Windows last version of VirtualBox and vagrant and run `vagrant up`

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Did you look at https://github.com/hassio-addons/hassio-vagrant#notes-for-windows-users

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/hassio-vagrant">hassio-addons/hassio-vagrant</a></strong></div><div>Vagrant box running Hass.io / Home Assistant. Contribute to hassio-addons/hassio-vagrant development by creating an account on GitHub.</div></blockquote>

**Comment by Limych** [comment]
I'm sorry, but I followed all the recommendations in this section exactly. Vagrant was launched from under powershell:
![image](https://user-images.githubusercontent.com/8019701/62321004-4cf3d900-b4aa-11e9-94f0-7fa200c503d3.png)

**Comment by sinclairpaul** [comment]
As I'm sure you can appreciate it's extremely difficult to troubleshoot local issues on workstations, and primarily this is a Dev tool, so won't always just work out of the box.  It's not really related to the vagrant script as it works for many other people.

The only suggestions I could make is that you may have the Windows Firewall blocking the connection or winnfsd.exe is already running (see the note on termination).  If that still doesn't work you can always uninstall the winnfsd extension and fall back to SMB.

Edit - also maybe try to shorten the file path for your vagrant setup.
