### ISSUE TITLE
Error during connection setup: database is locked

### ISSUE THREAD

**Issue by Limych** [hassio-addons/hassio-vagrant#36]
# Problem/Motivation

I can’t start the system. Constantly writes an error that the database is locked.

System: Linux Ubuntu 19.10
VirtualBox: 6.0.14
Vagrant: 2.2.3
Installed last versions of nfs-common and nfs-kernel-server packages

I tried the configurations of hassio-vagrant v1.2.0, v1.3.0 and master. In all cases, the symptoms are the same. Installation of the machine is error-free. Initial setup of the Home Assistant starts. After the initial setup, the system works normally. But if I initiate a restart of the virtual machine or a restart of the Home Assistant, everything breaks: it constantly gives the error message
```
ERROR (Recorder) [homeassistant.components.recorder] Error during connection setup: (sqlite3.OperationalError) database is locked
```

The database file always on disk is zero in size.
Deleting a database file does not change anything - it appears back, but the error remains.

It is treated (temporarily) only by a complete recreation of the machine.

**Comment by frenck** [comment]
Interesting, I do not own a Ubuntu/Debian/Linux workstation, so hard for me to reproduce. I'm open for PR's and fixes.

Nevertheless, I've personally created a fresh box every time I started working on add-ons (for which this repository is created).

**Comment by sinclairpaul** [comment]
I've seen similar issues on Windows where essentially Vagrant fails to mount the drives correctly after a halt.  I would suggest you first upgrade your Vagrant version (2.2.3 is nearly a year old now), and probably look for help in the Vagrant repo.

It's not likely to be an issue with the script here.

**Comment by Limych** [comment]
The fact of the matter is that I have the newest version installed:
```shell
limych:~$ LANG=en_US.UTF-8 && sudo apt install vagrant
Reading package lists... Done
Building dependency tree       
Reading state information... Done
vagrant is already the newest version (2.2.3+dfsg-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by sinclairpaul** [comment]
You have the latest version installed from the package manager....

**Comment by Limych** [comment]
Unfortunately, upgradation of vagrant are not solved the problem. :(

I've manually upgrade vagrant to the latest version 2.2.6 from official site.
Then updated 'ubuntu/bionic64' box to the latest version '20191218.0.0'.
Then I destroyed and recreated vagrant box.

The same error still have...

Perhaps it will help that when the box starts, it reports the following message:
```
==> hassio: Checking for guest additions in VM...
    hassio: The guest additions on this VM do not match the installed version of
    hassio: VirtualBox! In most cases this is fine, but in rare cases it can
    hassio: prevent things such as shared folders from working properly. If you see
    hassio: shared folder errors, please make sure the guest additions within the
    hassio: virtual machine match the version of VirtualBox you have installed on
    hassio: your host and reload your VM.
    hassio: 
    hassio: Guest Additions Version: 5.2.34
    hassio: VirtualBox Version: 6.0
```

**Comment by licarth** [comment]
Same problem here with Ubuntu 19.10 and :
VirtualBox 6.0.14 with extension pack
Vagrant 2.2.6

homeassistant docker logs :
```
2020-02-04 16:22:05 INFO (MainThread) [homeassistant.setup] Setting up recorder
2020-02-04 16:22:05 INFO (MainThread) [homeassistant.setup] Setting up webhook
2020-02-04 16:22:05 INFO (MainThread) [homeassistant.setup] Setup of domain webhook took 0.0 seconds.
2020-02-04 16:22:05 INFO (SyncWorker_7) [homeassistant.loader] Loaded alexa from homeassistant.components.alexa
2020-02-04 16:22:05 INFO (SyncWorker_5) [homeassistant.loader] Loaded google_assistant from homeassistant.components.google_assistant
2020-02-04 16:22:05 INFO (SyncWorker_8) [homeassistant.loader] Loaded camera from homeassistant.components.camera
2020-02-04 16:22:05 INFO (SyncWorker_4) [homeassistant.loader] Loaded media_player from homeassistant.components.media_player
2020-02-04 16:22:06 INFO (MainThread) [homeassistant.setup] Setting up cloud
2020-02-04 16:22:06 INFO (MainThread) [homeassistant.setup] Setup of domain cloud took 0.0 seconds.
2020-02-04 16:22:15 WARNING (MainThread) [homeassistant.setup] Setup of recorder is taking over 10 seconds.
2020-02-04 16:28:27 ERROR (Recorder) [homeassistant.components.recorder] Error during connection setup: (sqlite3.OperationalError) database is locked
(Background on this error at: http://sqlalche.me/e/e3q8) (retrying in 3 seconds)
```

**Comment by sinclairpaul** [comment]
Not sure what help can be provided for this, the repo provides a vagrant script to ease setting up a Dev environment.  Although personally I don't use it anymore, I believe the issue will likely be to do with the way Vagrant itself sets up the shared folders, you should not be rebooting the VM, but using the vagrant commands to halt the setup.  

I would suggest seeking more help at the vagrant repo itself https://github.com/hashicorp/vagrant

<blockquote><img src="https://avatars0.githubusercontent.com/u/761456?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hashicorp/vagrant">hashicorp/vagrant</a></strong></div><div>Vagrant is a tool for building and distributing development environments. - hashicorp/vagrant</div></blockquote>
