### ISSUE TITLE
Update URL for Hassio installer

### ISSUE THREAD

**Issue by jordanbean1** [hassio-addons/hassio-vagrant#37]
# Problem/Motivation

Unable to install Home Assistant using `vagrant up hassio` because the URL for the HASSIO_INSTALLER has changed.

## Expected behavior

`vagrant up hassio` successfully installs on the VM and starts

## Actual behavior

Vagrant fails to run and exits inside the "install_hassio" function due to the URL being changed.

`hassio: bash: line 1: 404:: command not found`

## Steps to reproduce

`vagrant up hassio` in a fresh install

## Proposed changes

Update the "provision.sh" file on line 18 to set the `HASSIO_INSTALLER` global variable to "https://raw.githubusercontent.com/home-assistant/supervised-installer/master/installer.sh"

<blockquote></blockquote>

**Comment by frenck** [comment]
Feel free to open up a PR to address the issue.
