### ISSUE TITLE
Provision fails due to change for user input in supervisored install script

### ISSUE THREAD

**Issue by alandtse** [hassio-addons/hassio-vagrant#41]
# Problem/Motivation

Provisioning fails because the `install_hassio` function fails to complete due to read request from https://raw.githubusercontent.com/home-assistant/supervised-installer/master/installer.sh.

## Expected behavior

Provisioning should complete.

## Actual behavior

Provisioning fails because user input is not provided.

```
    hassio: [warn] Changes are needed to the /etc/network/interfaces file
    hassio: [info] If you have modified the network on the host manualy, those can now be overwritten
    hassio: [info] If you do not overwrite this now you need to manually adjust it later
    hassio: [info] Do you want to proceed with overwriting the /etc/network/interfaces file? [N/y]
    hassio: bash: line 108: /dev/tty: No such device or address
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

## Steps to reproduce

`vagrant up` on a fresh system

## Proposed changes

> Proposed fix is to pipe yes into the script after download. I couldn't get it working presumably because the script requests from /dev/tty.
```bash
install_hassio() {
    curl -sL "${HASSIO_INSTALLER}" > /tmp/hassio.sh
    yes | bash /tmp/hassio.sh
}
```
> Work around is to manually log in to complete.

1. vagrant ssh
2. curl -sL "https://raw.githubusercontent.com/home-assistant/supervised-installer/master/installer.sh" | bash -s
3. hit y when prompted.

**Comment by frenck** [comment]
I've decided not to pursue a fix for this, but deprecating this repository instead.

See the repository README for more information on this.
