### ISSUE TITLE
Move SSH port to 22222

### ISSUE THREAD

**Issue by frenck** [hassio-addons/hassio-vagrant#5]
# Problem/Motivation

Currently, the box has running SSH on port 22, which causes direct issues when installing the SSH add-on.

## Proposed changes

Run the SSH server of the box on port 22222, which is similar to Hass.io installed on a Pi.

**Comment by danielwelch** [comment]
Love the project, great job.

I was going to take a stab at this, but after looking into it for a little it looks like it would require making changes to the base box.

Vagrant exposes [some ssh config options](https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html) and of course port forwarding configuration options in the `Vagrantfile`. I was hoping that `config.ssh.guest_port` was what I was looking for, but that just tells Vagrant what port to attempt to connect to. Setting it to something other than `22` causes SSH connection to fail.

I looked to see if this could be accomplished through `VBoxManage` or `vmx` (and thus through the `Vagrantfile`) but couldn't find anything. Any ideas?

**Comment by frenck** [comment]
I've taken a look as well, unless we are going to build our own Vagrant box image, this is not fixable.

The base images used are already on port 22. The initial setup/run expects it there. If we are changing the port, it needs to be done at a later stage. Nevertheless, at that point, it breaks Vagrant.

Therefore closing this issue.
